### PR TITLE
[add] ajustement volume avec molette de la souris

### PR DESCRIPTION
**Pull request by ysa000**
Ajustement du volume du player, lorsque le curseur survole la barre de volume et que la molette souris/scroll trackpad est activée
up pour augmenter le volume / down pour le diminuer

### CODE REVIEW

**Comment by jsilvestre** [comment]
@m4dz I tested it functionally and it works. Please merge it before tomorrow so it can be demonstrated <3

**Comment by m4dz** [comment]
@ysa000 Great, thanks 🎉 !

You've open your PR on your own repository instead of the cozy-labs:development one. Can you reopen it on cozy-lab? Thanks!

**Comment by m4dz** [comment]
@ysa000 as long this PR isn't releant, you can safely close it :)

**Comment by ysa000** [comment]
@m4dz Thanks for the tip !

**Comment by m4dz** [comment]
Ur welcome 🌮

**Pull request closed without merging**
